# Question
Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log('Inside the loop', i);
  }
  console.log('Outside the loop');
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer
Console.log('Outside the loop', i) will never print because we use the "return" statement which ends a function when it's executed. So nothing after the return will be executed. 

# Teacher Feedback

Yup!

Score: 3/3